[package]
name = "xtask"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
publish = false

[dependencies]
syn = { version = "2.0.114", features = ["full", "parsing", "visit"] }
quote = "1.0.43"
proc-macro2 = "1.0.105"
anyhow = "1.0"
walkdir = "2.5"
toml = "0.8"
semver = "1.0"
